added test sample

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -7,13 +7,13 @@ dart --version
 # dart analyze --fatal-infos --fatal-warnings lib test
 # dart test
 
-branch_name=$(git rev-parse --abbrev-ref HEAD)
+# branch_name=$(git rev-parse --abbrev-ref HEAD)
 
-if ! [[ $branch_name =~ ^(feat/|fix/|docs/|style/|refactor/|perf/|test/|build/|ci/|chore/|revert/).+ ]]; then
-  echo "Invalid branch name. Branch names must start with one of the following prefixes followed by a forward slash:"
-  echo "feat/, fix/, docs/, style/, refactor/, perf/, test/, build/, ci/, chore/, revert/"
-  echo "Example: feat/new-feature"
-  exit 1
-fi
+# if ! [[ $branch_name =~ ^(feat/|fix/|docs/|style/|refactor/|perf/|test/|build/|ci/|chore/|revert/).+ ]]; then
+#   echo "Invalid branch name. Branch names must start with one of the following prefixes followed by a forward slash:"
+#   echo "feat/, fix/, docs/, style/, refactor/, perf/, test/, build/, ci/, chore/, revert/"
+#   echo "Example: feat/new-feature"
+#   exit 1
+# fi
 
 
