Commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,7 +2,21 @@
 
 . "$(dirname -- "$0")/_/husky.sh"
 
-dart --version
+# Find the absolute path to the fvm command
+FVM_PATH=$(command -v fvm)
+
+# Check if fvm command is found
+if [ -n "$FVM_PATH" ]; then
+  # Add the directory containing the fvm command to PATH
+  export PATH="$(dirname "$FVM_PATH"):$PATH"
+else
+  echo "FVM not found. Please make sure it is installed and accessible."
+  exit 1
+fi
+
+dart run lint_staged
+
+
 # dart format --line-length 80 --set-exit-if-changed lib test
 # dart analyze --fatal-infos --fatal-warnings lib test
 # dart test
